[TRH-39] CLASS MATRIX
11AgReS1SoR11/TransHub pull request #14
Opened 2024-03-24 09:34 UTC by GachiBoy0706

набросал реализацию класса матриц

2024-03-24 09:51 UTC, 11AgReS1SoR11 requested changes

2024-03-24 09:51 UTC, 11AgReS1SoR11 commented on Common/Matrix/matrix.h
> +    };
Здесь нужно убарть ;

2024-03-24 09:51 UTC, 11AgReS1SoR11 commented on Common/Matrix/matrix.h
> +        return Matric(ans);    };
`Matric`?

2024-03-24 09:51 UTC, 11AgReS1SoR11 commented on Common/Matrix/matrix.h
> +            if (n == 1) {
Табулияция съехала

2024-03-24 09:51 UTC, 11AgReS1SoR11 commented on Common/Matrix/matrix.h
> +    bool match_sizes(Matrix& first_matrix, Matrix& second_matrix){
Здесь нужно по константной ссылке

2024-03-24 09:51 UTC, 11AgReS1SoR11 commented on Common/Matrix/matrix.h
> +    void print(){
const noexcept

2024-03-24 09:51 UTC, 11AgReS1SoR11 commented on Common/Matrix/matrix.h
> +        return Matrix(ans);
Тут происходит лишнее копирование, поэтому лучше использовать изначально вектор матрицы, которую будешь возвращать, и тогда сработает RVO или написать констроктор от rvalue std::vector и смувать туда

2024-03-24 09:51 UTC, 11AgReS1SoR11 commented on Common/Matrix/matrix.h
> +#ifndef MATRIX_H
Предлагаю переименновать `matrix.h` -> `matrix.hpp`

2024-03-24 09:51 UTC, 11AgReS1SoR11 commented on Common/Matrix/matrix.h
> +    Matrix operator * (Matrix& other_matrix){
принимай по const ссылке и реши проблему с лишним копированием веткора

2024-03-26 10:24 UTC, 11AgReS1SoR11 requested changes

2024-03-26 10:24 UTC, 11AgReS1SoR11 commented on Common/Matrix/test/test.cpp
> +    mat1.print();
Принт в тестах не нужен. Они будут фоном запускаться, чтобы проверять, что ничего не сломалось, поэтому, чтобы не захломлять лог, предлагаю это убрать

2024-03-26 10:24 UTC, 11AgReS1SoR11 commented on Common/Matrix/test/test.cpp
> +    std::cout << "Determinant: " << mat3.determinant() << std::endl;
В чём заключается тест? Ты создал матрицу от двух матриц, но не проверяешь, что у тебя получилось. И детерминант лучше вынести в одтельный тест и тоже проверять.
Проверять можешь через QVERIFY(smth == smth2)

2024-03-26 10:24 UTC, 11AgReS1SoR11 commented on Common/Matrix/test/test.cpp
> +    //Matrix mat3(vec3);
Коменты надо стереть

2024-03-26 10:24 UTC, 11AgReS1SoR11 commented on Common/Matrix/test/test.cpp
> +    Matrix mat4(mat2 * mat1);
То же самое, ты не проверяешь, какая матрица у тебя получилась, а только выводишь её.
Вывод убери
Проверку добавь

2024-03-26 10:24 UTC, 11AgReS1SoR11 commented on Common/Matrix/test/test.cpp
> +    QVERIFY_EXCEPTION_THROWN(Matrix mat1(vec1), std::runtime_error);
Вот тут хорошо, а этот макрос может сообщение ошибки выводить?

2024-03-26 10:24 UTC, 11AgReS1SoR11 commented on Common/Matrix/src/matrix.h
> +    static double det(const std::vector<std::vector<T>>& matrix);
Это хорошо сделано, у determinant должен быть аналог, который не принадлежит к классу, а просто принимает матрицу, поэтому вынеси в public и принимать матрицу, а не вектор векторов, учитывая (у этой функции есть доступ к приватным полям, там и вытащишь)

2024-03-26 10:24 UTC, 11AgReS1SoR11 commented on Common/Matrix/src/matrix.h
> +    Matrix operator * (const Matrix& other_matrix);
Эти операции тоже не меняют состояние матрицы, поэтому тоже const

2024-03-26 10:24 UTC, 11AgReS1SoR11 commented on Common/Matrix/src/matrix.h
> +    void print() const noexcept;
Добавь этой функции также static аналог как с детерминантом

2024-03-26 11:27 UTC, GachiBoy0706 commented on Common/Matrix/src/matrix.h
> +    static double det(const std::vector<std::vector<T>>& matrix);
не понял, надо сделать фунцию расчета детерминанта не методом класса?

2024-03-26 11:30 UTC, GachiBoy0706 commented on Common/Matrix/src/matrix.h
> +    static double det(const std::vector<std::vector<T>>& matrix);
det нужен, чтобы рекурсивно определитель считать, а не чтобы его вне класса вызывать (поэтому в privat секции он лежит)

2024-03-26 12:02 UTC, 11AgReS1SoR11 commented on Common/Matrix/src/matrix.h
> +    std::vector<std::vector<T>> mat(this->_data);
Зачем здесь делать копирование, сделай просто `return Matrix<t>::det(this->_data)`

2024-03-26 12:02 UTC, 11AgReS1SoR11 commented on Common/Matrix/src/matrix.h
> +    static double det(const std::vector<std::vector<T>>& matrix);
Ааа, понял, какая там логика, да, тогда оставляй как есть

2024-03-26 12:05 UTC, 11AgReS1SoR11 commented on Common/Matrix/src/matrix.h
> +
И ты не обернул этот класс в namespace Matrix

2024-03-26 13:25 UTC, GachiBoy0706 commented on Common/Matrix/test/test.cpp
> +    QVERIFY_EXCEPTION_THROWN(Matrix mat1(vec1), std::runtime_error);
Этот макросс может только проверять тип исключения, к сообщению об ошибке через него доступ не получить

2024-03-26 14:31 UTC, 11AgReS1SoR11 commented on Common/Matrix/test/test.cpp
> +    mat1.print();
Добавь тест на детерминант и на эксепшент операции + и убери этот принт

2024-03-26 14:37 UTC, 11AgReS1SoR11 commented on Common/Matrix/test/test.cpp
> +using namespace Matrix
Здесь должна быть `;`

2024-03-26 15:12 UTC, 11AgReS1SoR11 commented
Красота, а Matrix_global.h нам нужен?

2024-03-26 15:12 UTC, 11AgReS1SoR11 approved these changes

2024-03-26 18:37 UTC, merged