[TRH-68] Jordan-Gauss Method for Matrix component
11AgReS1SoR11/TransHub pull request #29
Opened 2024-04-17 19:42 UTC by GachiBoy0706

Добавлен метод жордана-гаусса для решения слау

2024-04-18 10:30 UTC, 11AgReS1SoR11 requested changes

2024-04-18 10:30 UTC, 11AgReS1SoR11 commented on Common/ComponentMatrix/src/Matrix.hpp
> +        // Создаем расширенную матрицу [A | b]
Отступы поехали, выглядит криво

2024-04-18 10:30 UTC, 11AgReS1SoR11 commented on Common/ComponentMatrix/test/test.cpp
> +    QVERIFY_EXCEPTION_THROWN(Mtx::Matrix<double>::solve(mat1, b), QException);
Здесь бы комментарием добавить с каким сообщением исключение, а то не понятно и добавить тест на исключение, когда размеры не совпадают

2024-04-18 10:30 UTC, 11AgReS1SoR11 commented on Common/ComponentMatrix/test/test.cpp
> +    Matrix mat1(vec1);
Ты здесь лишний раз копируешь, можно же просто написать:
Matrix mat1 = {
        {1, 2, 3},
        {4, 5, 6},
        {7, 8, 9}
 };

2024-04-18 10:30 UTC, 11AgReS1SoR11 commented on Common/ComponentMatrix/src/Matrix.hpp
> +            if (divisor != 0)
1) Можно красивее `if (double divisor = augmentedMatrix[i][i]; divisor != 0)` потому что используешь только в теле if
2) double нельзя так сравнивать, потому что там плавающая точность, нужно сравнивать по модулю с epsilon

2024-04-18 10:30 UTC, 11AgReS1SoR11 commented on Common/ComponentMatrix/src/Matrix.hpp
> +    int n = sqrt(A.size());
Зачем тебе нужен метод size(), если ты выше проверил, что у тебя матрица квадратная, сделай просто
`int n = A._rows` а этот метод удали

2024-04-18 10:43 UTC, 11AgReS1SoR11 commented on Common/ComponentMatrix/src/Matrix.hpp
> +        QVector<QVector<T>> augmentedVector(n, QVector<T>(n + 1));
Если ты не трогаешь сам вектор b и матрицу A, то зачем принимаешь по значению? Либо принимай по ссылке и делай большую матрицу копируя всё или принимай по значению и с ними работай (не создавай общую матрицу)

2024-04-19 06:27 UTC, 11AgReS1SoR11 requested changes

2024-04-19 06:27 UTC, 11AgReS1SoR11 commented on Common/ComponentMatrix/src/Matrix.hpp
> +    int size() const noexcept;
Удали этот метод, не представляю, когда нам может пригодится умножение rows * columns

2024-04-19 06:27 UTC, 11AgReS1SoR11 commented on Common/ComponentMatrix/src/Matrix.hpp
> +    double eps = 0.0001;
const

2024-04-19 06:27 UTC, 11AgReS1SoR11 commented on Common/ComponentMatrix/src/Matrix.hpp
> +                    if (augmentedMatrix[k][j] != 0)
Здесь и ниже тоже через epsilon

2024-04-19 06:27 UTC, 11AgReS1SoR11 commented on Common/ComponentMatrix/src/Matrix.hpp
> +            bool flag = true; //flag that signalizes if there zero-row in matrix
Что-то с отступами, пофикси здесь и ниже

2024-04-19 08:14 UTC, GachiBoy0706 commented on Common/ComponentMatrix/src/Matrix.hpp
> +    int size() const noexcept;
он в коде испольузется, в миноре например

2024-04-19 08:41 UTC, 11AgReS1SoR11 commented on Common/ComponentMatrix/src/Matrix.hpp
> +    int size() const noexcept;
Ты его добавил в этом PR и нигде в этом PR не используешь. + я уверен, что в будущем его никто не будет использовать, потому что это useless метод какой-то

2024-04-19 08:43 UTC, 11AgReS1SoR11 approved these changes
Уменьши epsilon до 10-8 хотя бы и удали метод size, а так больше вопросов нет

2024-04-19 09:06 UTC, merged